Resources:
  ApiGatewayCognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: COGNITO_AUTHORIZER
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId:
        Ref: ApiGatewayRestApi
      ProviderARNs:
        - arn:aws:cognito-idp:us-east-1:533266970081:userpool/us-east-1_qHpxVDXhq
