Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: episteme-notesTable-${sls:stage}
      KeySchema:
        -
          AttributeName: pk
          KeyType: HASH
        -
          AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        -
          AttributeType: S
          AttributeName: pk
        -
          AttributeType: S
          AttributeName: sk
      BillingMode: PAY_PER_REQUEST
